name: Build application (Windows)

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build-windows.yml"
            - package.json
    workflow_dispatch:
    create:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Node.js dependencies
              run: npm install

            - name: Build the application
              run: npm run build

            - name: Compress Windows build artifacts (x64)
              run: powershell Compress-Archive -Path build\SlimeTora-win32-x64\* -DestinationPath build\SlimeTora-win32-x64.zip

            - name: Compress Windows build artifacts (arm64)
              run: powershell Compress-Archive -Path build\SlimeTora-win32-arm64\* -DestinationPath build\SlimeTora-win32-arm64.zip

            - name: Archive build artifacts for Windows (x64)
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts-win32-x64
                  path: build/SlimeTora-win32-x64.zip

            - name: Archive build artifacts for Windows (arm64)
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts-win32-arm64
                  path: build/SlimeTora-win32-arm64.zip
